### ISSUE TITLE
Warning (Orange) message support

### ISSUE THREAD

**Issue by rizwan-ishtiaq** [alexpermiakov/simple-react-notifications#5]
It will be nice if you can add support for warning message (notifier.warn())
It should display message in orange. I know one can write custom for that. But you have to do very minimum change (as i have seen the code) and this feature will be available out of the box

**Comment by alexpermyakov** [comment]
Sorry for the long response! Would be great if you can create a PR for it.

**Comment by rizwan-ishtiaq** [comment]
created a pull request, kindly have a look
https://github.com/alexpermyakov/simple-react-notifications/pull/7

**Comment by rizwan-ishtiaq** [comment]
When it should available on package manager?

**Comment by rizwan-ishtiaq** [comment]
Hello everyone,
As Alex seem busy and not responding anything
i have created a fork of this repo and maintaining it with name "simple-react-notifications2"
https://github.com/rizwan-ishtiaq/simple-react-notifications2
you can use this to get latest version from npm
